export const GAME = {
  TUNING: {
    LIVES_START: 10,
    SPAWN_INTERVAL_START: 3,
    SPAWN_INTERVAL_MIN: 1.5,
    SPAWN_INTERVAL_RAMP_PER_SEC: 1 / 40,
    FAULTS_TIER_2_AT: 45,
    FAULTS_TIER_3_AT: 90,
    SCORE_PER_FIX: 100,
  }
}
