export const GAME = {
  TUNING: {
    LIVES_START: 10,
    SPAWN_INTERVAL_START: 4,
    SPAWN_INTERVAL_MIN: 2.7,
    SPAWN_INTERVAL_RAMP_PER_SEC: 1 / 75,
    FAULTS_TIER_2_AT: 30,
    FAULTS_TIER_3_AT: 60,
    SCORE_PER_FIX: 100,
  }
}
