export const DRAG = {
  LAYOUT: {
    PIECE_SIZE_PCT: 0.1,
    SLOT_SIZE_PCT: 0.12,
    START_OFFSET_X_PCT: -0.15,
    SLOT_OFFSET_X_PCT: 0.15,
    STROKE_WIDTH: 2,
    SNAP_TOLERANCE_PCT: 0.35,
  }
}
